### ISSUE TITLE
Suggestion to add `useSelectors`

### ISSUE THREAD

**Issue by chrisrzhou** [dai-shi/react-tracked#15]
Hey @dai-shi, love this package and the work you're doing here.  This solves the context re-rendering problem really elegantly.

Just a suggestion if we should add an additional API method called `useSelectors`.  It takes an array of selectors as input and outputs an array of selected states that can be accessed via destructuring:

```js
const [a, b, c] = useSelectors(getA, getB, getC);  // it can call `useSelector` under the hood.
```

Currently, to do this, we would use multiple lines of `useSelector`.  Obviously, users can implement `useSelectors` themselves but just wanted to check if it's worthwhile to include in this library!

**Comment by dai-shi** [comment]
Hi, thanks for your interest and suggestion.

I have two points to note:

1) My recommendation in this library is to use `useTrackedState` instead of `useSelector`. If you just want a selector interface without tracking, check out another library of mine: https://github.com/dai-shi/use-context-selector

2) The reason we have `useSelector` in this library is to ease transition from/to react-redux/reactive-react-redux. In the long discussion while developing hooks in react-redux, they decided to only provide `useSelector` which is a primitive. There was a certain demand to support `useActions` in the library, but they provided it as a recipe. So, I think it's fair to suggest uses to implement `useSelectors` by themselves.

How does these sound?

**Comment by chrisrzhou** [comment]
Totally, thanks for the context! On my side, `useSelector` seemed intuitive to me coming from `react-redux`.

**Comment by dai-shi** [comment]
Please check out `useTrackedState` too. I'm interested in how people from react-redux see it.

BTW, I wonder if you already looked at reactive-react-redux.
