### ISSUE TITLE
[Question]Why child component still rerender?

### ISSUE THREAD

**Issue by TrendAlan** [dai-shi/react-tracked#153]
I change the "count" state in parent componet, but why the child component with "name" state still rerender?
Do I miss something?

You can check this [example](https://codesandbox.io/s/jolly-meninsky-32cd6h?file=/src/App.js)

**Comment by dai-shi** [comment]
It's how react render behaves. You want to wrap ChildName with `React.memo` too. (Or, make it stable with `{children}` or something, which is recommended in general before React.memo. cf. https://overreacted.io/before-you-memo/)

https://codesandbox.io/s/mystifying-williamson-se8nmt

**Comment by TrendAlan** [comment]
ok, I add memo to the child name component, and the timestamp will not change anymore.
But from what I understand the console.log("xxx") in child name component should not run too.
What is the difference with this [example](https://codesandbox.io/s/delicate-pine-y23cbj?file=/src/childName.js)
You can see that the console.log() will not run in child count component, and this is the 3rd methods mentioned in your [blog](https://blog.axlight.com/posts/4-options-to-prevent-extra-rerenders-with-react-context/)

**Comment by dai-shi** [comment]
Hmm, this is not too surprising to me because extra render without commits is generally a technique I use in react-tracked (and internally use-context-selector). I'd generally recommend putting console.log in useEffect.

https://codesandbox.io/s/beautiful-shaw-6lde0t?file=/src/childName.js

---

But, now I can't explain well which code exactly causes this behavior, given that we don't use `{ concurrentMode: true }` in createContainer.

Oh okay, this seems like a behavior changed in React 18. Here's the same one with React 17: https://codesandbox.io/s/vibrant-butterfly-nimklh?file=/src/index.js

**Comment by TrendAlan** [comment]
Great, thank you so much for clear explain.
It's really an awesome package.
