### ISSUE TITLE
Comparison with proxy-state-tree

### ISSUE THREAD

**Issue by joelmoss** [dai-shi/react-tracked#45]
I came across [overmind](https://github.com/cerebral/overmind) the other day, and their [proxy-state-tree](https://github.com/cerebral/overmind/tree/next/packages/node_modules/proxy-state-tree) library that seems to do the same thing as `useTrackedState()` does.

So I was wandering if you were familiar with it, and how it compares.

thx 👍

**Comment by dai-shi** [comment]
Hi,
I know roughly how proxy-state-tree works. There was a bit of discussion while developing reactive-react-redux in early days.

Basically, it's similar. There's a big difference in design choices. MobX and proxy-state-tree are based on mutable objects, where as react-tracked and reactive-react-redux are based on immutable objects. Does it make sense?

In general, mutable object approach can be a little bit faster because we can reuse Proxies. Immutable object approach is better to support Concurrent Mode, I believe.

For your information, I already split the tracking library to [proxy-compare](https://github.com/dai-shi/proxy-compare) (whose README notes similar libraries), and react-tracked v2 depends on it. #43

**Comment by dai-shi** [comment]
Closing as resolved.
