### ISSUE TITLE
Problems of updating my component after updating the context

### ISSUE THREAD

**Issue by suanmei** [dai-shi/react-tracked#48]
I used `useReducer`, and the hierarchy of context(trackedState)  is deepermy. When I updated one of the values，for example

```
const changeType = (state: SchemaState, keyRoute: KeyRoute, fieldType: SchemaType): SchemaState => {
  // set field new value
  set(state, keyRoute, defaultSchema[fieldType]);

  return state;
};
```

My component used this value don't update.

So, I force return a value after deep copy

```
const changeType = (state: SchemaState, keyRoute: KeyRoute, fieldType: SchemaType): SchemaState => {
  const schema = cloneDeep(state);

  // set field new value
  set(schema, keyRoute, defaultSchema[fieldType]);

  return schema;
};
```

But, no i face a new problem，some of the elements on my page have `onblur` event, some have `onclick` events. Sometimes they will trigger at the same time. 

Because of deep copying, only one of the two dispatches can take effect

Can you give me some good suggestions？

**Comment by dai-shi** [comment]
Hi, thanks for opening a discussion.
It's not very clear how your `useReducer` and `set` look like. If you could share a small reproduction, it would be so much helpful.

That said, here's an answer based on my assumption: We need to update state immutably. Please don't mutate / don't deep copy. If you are not very familiar with this pattern, `immer` would be a good lib to help with it.

I could explain a little more with code, but since I might misunderstand your use case, I'd wait for your response and a concrete example.

**Comment by suanmei** [comment]
Thanks for your reply!
This is my use of `useReducer`:
https://github.com/suanmei/iMove/blob/suanmei/packages/json-schema-editor/src/store/schema.ts
use of `dispatch/set`:
https://github.com/suanmei/iMove/blob/suanmei/packages/json-schema-editor/src/reducer/schema.ts

My `state` is dynamic,  and I think my usage is indeed problematic

I will research if immer can solve my problem

**Comment by dai-shi** [comment]
OK, so the `set` is from lodash.
You might also want to check out lodash/fp.
- https://github.com/lodash/lodash/issues/1696
- https://github.com/lodash/lodash/wiki/FP-Guide

(Note: I have no deep experience with it.)

**Comment by suanmei** [comment]
Thanks again for your suggestions, the performance of my components has indeed improved.
