### ISSUE TITLE
Usage without <Provider />

### ISSUE THREAD

**Issue by natew** [dai-shi/react-tracked#62]
Would it be possible to use this without provider, at least as an option? Would help me with an abstraction I'm attempting to build.

**Comment by natew** [comment]
I suppose I could have one big global store behind the scenes and just use pieces of it as needed... any performance downsides there?

**Comment by dai-shi** [comment]
React Tracked is based on Context API and Provider is a fundamental building block.

Note: There are two types of libraries for global state. (1) React state (2) External state

> I suppose I could have one big global store behind the scenes and just use pieces of it as needed... any performance downsides there?

That's exactly the primary use case. It would work like a magic.
If you can split state into pieces in advance, you can use bare Context (a context for each piece). It's the recommended pattern in general. So, the use case of this library is when that is not possible or desirable. `{ firstName: 'Harry', familyName: 'Potter' }` is a tiny example you don't want to split.

**Comment by natew** [comment]
Ok, thanks for getting back quickly. Just to confirm, I would end up with one very large object provided once at the root, initially with an empty object `{}` and then as I mount various things, I would then just attach the state I need onto the root object using a "fake" namespace. So, if I was adding some state `{ name: 'Nate', lastName: 'Potter' }` in some local component, I would map it to `{ localid_name: 'Nate', localid_lastName: 'Potter' }`. The entire app would basically do this for all its state, so you could potentially have hundreds/thousands of keys on that object.

Would I be running into an `O(n)` where n is the number of items on the state performance slowdowns? Or, is it as I hope, where the number of "listened to keys" would be the relevant factor, and it doesn't matter how many I place at the top. I should really read over the code more thoroughly, but it is helpful to sanity check with the author that this use case won't become bad at some point.

**Comment by dai-shi** [comment]
First things first, it's very hard to discuss about performance in general. We would need to measure it.

That said, it's JS issue. If `obj[prop]` is `O(n)`, then it's probably so. There's no magic there. We use Proxies, but the order should be the same (it depends on the complexity of `WeakMap`). In your example `{ localid: { name: 'foo', lastName: 'bar' } }` would be better.

> this use case won't become bad at some point.

What I can tell is it's an expected use case. A thousand items should be fine. A million items, not sure. In such a case, tree structure would be better, instead of flat list.

**Comment by natew** [comment]
Thank you so much, you've been a great help to React development.

**Comment by natew** [comment]
Last question based on your nested comment:

```
{ localid: { name: 'foo', lastName: 'bar' } }
```

When I change just `localid.name` to `baz` and in a component I access `state.localid.name`.

I assume that would re-render, but if I access `state.localid.lastName` it would not... in specific cases? Basically, whats the affect in the *reducer* of the tracking, do any of these save performance:

```ts
state.localid.name = 'baz'
return state
```

vs:

```ts
state.localid = { ...state.localid, name: 'baz' } 
return state
```

vs:

```ts
return {
  localid: {
    ...state.localid,
    name: 'baz'
  }
  ...state,
}
```

**Comment by dai-shi** [comment]
I should have mention that the basis of React Tracked is immutable state. It's optimized for it.
So, only the last one behaves correctly. If you mutate an object, React Tracked can't detect it because the reference is the same, and it behaves like the object is unchanged.

If you prefer the mutating style, please consider using immer.

Hope it makes sense.
