### ISSUE TITLE
How can I return multiple useState or functions with custom hook?

### ISSUE THREAD

**Issue by rimsila** [dai-shi/react-tracked#65]
Hi  @dai-shi , I'm very interested about your library I also used to use react-global-state-hook. Now I move to React-tracked and I have a question  about it I want to return count1 and setCountOrig1, delPosts  also. What can I do? thanks you
```
//custom hook  I used to do like this before:
return {
   delPosts ,
    count, 
    setCoun,
    count1,
    setCountOrig1 
  };
```
Example :
```
import { createContainer } from 'react-tracked';
const useValue = () => {
  const [count, setCountOrig] = useState(0);
  const [count1, setCountOrig1] = useState(0);

  const setCount = (nextCount: number) => {
    // eslint-disable-next-line no-console
    console.log({ nextCount });
    setCountOrig(nextCount);
  };

  //delete posts
  const delPosts = useCallback(
    async id => {
      const newData = filter(dataPosts?.data, o => o.id !== id);
      mutatePosts({ ...dataPosts, data: [...newData] });
      await api.delPosts(id);
      //refetch
      refreshPosts();
    },
    [dataPosts, mutatePosts, refreshPosts]
  );
  return [count, setCount] as const;

const { Provider, useTracked } = createContainer(useValue);

```

**Comment by dai-shi** [comment]
Hi, very good point. The current version requires a single function for the updating function.
I would do something like this.

```js
const useValue = () => {
  ...
  const setCount = ...
  const delPosts = ...
  const update = useCallback((type, ...args) => {
    if (type === 'setCount') setCount(...args);
    if (type === 'delPosts') delPosts(...args);
  }, [setCount, delPosts]);
  return [count, update];

};
```

You could then split in a hook.

```js
const useMyUpdate = () => {
  const update = useUpdate(); // from the container
  const setCount = useCallback((...args) => update('setCount', ...args), [update]);
  const delPosts = useCallback((...args) => update('delPosts', ...args), [update]);
  return { setCount, delPosts };
};
```

Hope it helps.

**Comment by rimsila** [comment]
I still not clear about it  for useMyUpdate will use in render (counter) part right. I have try but still confuse . here is my  [codesandbox](https://codesandbox.io/s/xenodochial-night-kfqy6?file=/src/index.tsx)

**Comment by dai-shi** [comment]
Here's the modified sandbox: https://codesandbox.io/s/pensive-borg-slwpg

You can do it without `useCallback`, but please be aware that the functions are not referentially stable (like you can't put them in useEffect deps, without causing infinite loop.)

**Comment by rimsila** [comment]
It's working thanks you so much.

**Comment by seanblonien** [comment]
Here to say that I think supporting multiple update functions would be great and make conversion of normal context to `react-tracked` much easier.

Context in my app provides state values, derived state values, _and_ multiple mutator methods for mutating state all in the same context. 

Example:
```ts
type NotificationContext = {
  notifications: Notification[];
  isMinimized: boolean;
  addNotification: (notification: Notification, noDuplicate?: boolean) => void;
  removeNotification: (notification: Notification);
  clearErrorNotifcations: () => void;
  setIsMinimized: (isMinimized: boolean) => void;
}

export const NotificationContextProvider = () => {
  const [notifications, setNotifications] = useState([]);
  const [isMinimized, setIsMinimized] = useState(false);
 
  // addNotification...
  // removeNotification...
  // clearErrorNotifcations...

  return (
    <NotificationContext.Provider
      value={{
        notifications,
        isMinimized,
        addNotification,
        removeNotification,
        clearErrorNotifcations,
        // ...
      }}
    >
      {children}
    </NotificationContext.Provider>
  );
}
```

I am now aware I highly coupled the state values with the update/mutate methods on those state values, which seems to be a very different philosophy than this library suggests. I assume I am not the only one doing this pattern (or antipattern), so I doubt I'm alone in this usage of context. I agree making the mutate logic exist in custom hooks _outside_ of the actual context that tracks the state makes way more sense because the functions don't really need to be tracked in context state. _BUT_, the architecture is already like this and it'd be a re-write of the context and how it's consumed altogether for it to fit into this library's `createContainer` API.

You may be asking if there are multiple state values, can't I just shove that into a single deeply nested state value? Yes, I can definitely do that and have been, but I can't do the same for those multiple update methods as the second return value of the `createContainer`'s `useValue` hook arg.

Also, these contexts I have simply use `useState` for storing the actual state instead of `useReducer`. This means the complex multiple-value update methods use `setState` directly in the context provider definition (e.g.  `addNotification` or `removeNotification`). So you may say "_just use `useReducer`, that is the point of them to dispatch complicated state updates based on a payload an action type_", to which I say, that's effectively what I am doing, the "selector" logic just happens in what update method I choose to destructure/use from the context. The functionality is still abstracted like a reducer pattern, but the selector logic happens in the consuming code instead of the reducer. I think it's a perfectly fine pattern and has scaled very well so far, so the `createContainer` API not allowing for such a pattern is a slight bummer.

I tried "ignoring" the 2nd value of the `createContainer`'s `useValue` hook, meaning I just did 
```ts
return [{ /* all of those state values from above */}, () => ({})]
``` 
but that totally broke it, and I assume defeats the whole purpose of the required interface of createContainer, altho it did give me the correct looking state value for a brief time. Then I tried storing the whole context value in a new `useState` hook (including the derived values and mutators), but then it infinitely updates even tho all functions and values are either in `useCallback` or `useMemo` (altho I probably missed a few thinking back, the example I did it on was more complicated). Anyways that version looked extremely ugly, so that is not worth the workaround anyways if I did get it to work.

Any suggestions to best convert this context pattern to `react-tracked` with minimal semantics/interface changes?

**Comment by dai-shi** [comment]
Yeah, if we don't care a subtle behavior in concurrent rendering, we can ignore the second value and add functions in the state.
`useMemo` can't be avoided, but otherwise DX doesn't seem too bad???
```js
const useValue = () => {
  const [notifications, setNotifications] = useState([]);
  const [isMinimized, setIsMinimized] = useState(false);
  return useMemo(() => {
    // addNotification...
    // removeNotification...
    // clearErrorNotifcations...
    return [{
      notifications,
      isMinimized,
      addNotification,
      removeNotification,
      clearErrorNotifcations,
      // ...
    }, () => {
      throw new Error('use functions in the state')
    }];
  }, [...]);
};
```

**Comment by seanblonien** [comment]
Oh great this does work! 

Turns out I just needed to wrap a method in useCallback to prevent the infinite re-render problem. And for now yea I don't imagine my use case needs full concurrent rendering support so this will work great. I'd probably just convert to using the normal pattern of this library whenever that functionality needs to be supported

**Comment by dai-shi** [comment]
Great. And, I noticed the subtle concurrent rendering support is "off" by default 😓 , because it behaves a little weirdly in the legacy mode.

So, I think it's worth documenting as a recipe.

**Comment by dai-shi** [comment]
@seanblonien Would you quickly review #127?
Yeah, I too noticed that `useCallback` is necessary.
